---
title: "A comparetive study on PCR, PLS, Envelope and BayesPLS models"
author: "Raju Rimal"
date: "4 September 2016"
output:
  beamer_presentation:
    colortheme: seahorse
    fonttheme: professionalfonts
    highlight: tango
    includes:
      in_header: header.tex
    keep_tex: yes
    theme: Madrid
  ioslides_presentation:
    logo: LogoNMBU.png
    smaller: no
    widescreen: yes
  slidy_presentation:
    highlight: tango
csl: numeric
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

* Background
* Estimation methods under comparison
* Data Simulation
* Analysis, Results and Discussions

## Background

> * PLS Population Model [@helland1990partial] which further discussed by [@naes1993relevant; @helland2001some]
> * PLS, heavely developed [@wold1985partial; @naes1993relevant; @de1993simpls], without addressing the population model [@cook2013envelopes]
  > - Mostly popular among chemometrician
  > - PLS helped to develope the field of chemometrics in its current state (Munc et.al 2010)
  > - Was not very popular among statician which has changed and is nowadays considered as an essential tool for multivariate analysis
> * Accounting the population model, new estimation methods have been purposed such as Envelope (cook, 2010) and BayesPLS (Halland, Solve) which are closely related to PLS
> * Cook, Halland, Su, 2013 said that PLS is fundamentally an envelope in the population model

## Background

> * This study attempts to make an emperial comparison among PCR, PLS, Envelope and BayesPLS model on the basis of their prediction ability
> * Using `simrel` (Solve, 2013) R-package, data with diverse nature are simulated.
> * `simrel` allows to have control over latent structure (relevant component) of the data, fine analysis of strength and weekness of a models is possible

# Estimation Methods

## Principal Component Regression

$$\hat{\beta} = P(T^tT)^{-1}T^tY$$

## Partial Least Squares

$$
\hat{\beta}_A = \hat{W}_A\left(\hat{W}_A^TS_{xx}\hat{W}_A\right)^{-1}\hat{W}_A^Ts_{xy}
$$ 

where at each iteration,
$$\hat{W}_{A+1} = s_{xy} - S_{xx}\hat{W}_A\left(\hat{W}_A^TS_{xx}\hat{W}_A\right)^{-1}\hat{W}_A^Ts_{xy}$$

starting with, $\hat{W}_0 = s_{xy}$

## Envelope Method
## Bayesian Partial Least Square

# Data Simulation
## Simulation and Parameter Design

# Prediction Error
## Training and Test Prediction Error

# Analysis Results
## A Comparison with Prediction Error

# Conclusion
## Conclusion

# References

## References